### ISSUE TITLE
modul Image missing

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#42]
i can't determine if thats comming from django or Node but this is the error:
```
pi@babybuddy:/var/www/babybuddy/public $ gulp collectstatic
[23:07:51] Using gulpfile /var/www/babybuddy/public/gulpfile.js
[23:07:51] Starting 'collectstatic'...
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/easy_thumbnails/utils.py", line 11, in <module>
    from PIL import Image
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/easy_thumbnails/models.py", line 6, in <module>
    from easy_thumbnails import utils, signal_handlers
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/easy_thumbnails/utils.py", line 13, in <module>
    import Image
ImportError: No module named 'Image'
[23:07:56] 'collectstatic' errored after 4.63 s
[23:07:56] Error: 1
    at formatError (/usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/format-error.js:20:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/var/www/babybuddy/public/node_modules/orchestrator/index.js:264:8)
    at /var/www/babybuddy/public/node_modules/orchestrator/index.js:275:23
    at finish (/var/www/babybuddy/public/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/var/www/babybuddy/public/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
```
Version:
```
pi@babybuddy:/var/www/babybuddy/public $ node -v
v8.11.1
```

**Comment by cdubz** [comment]
Coming from Python via the [easy-thumbnails](https://pypi.org/project/easy-thumbnails/) dependency [Pillow](https://pypi.org/project/Pillow/). I'm guessing this is some issue with the ARM build process. I'm going to poke around more with my Pi to see if I can figure anything out.

**Comment by cdubz** [comment]
I haven't test this (I still can't get past `pipenv install`), but here's a potential workaround:

`sudo apt-get install libopenjp2-7-dev`

Source: [Pillow: libopenjp2.so.7: cannot open shared object file: No such file or directory](https://stackoverflow.com/questions/48012582/pillow-libopenjp2-so-7-cannot-open-shared-object-file-no-such-file-or-directo)

**Comment by cdubz** [comment]
Confirmed this resolves for ARM. Closing this and tracking in #43.
