### ISSUE TITLE
Best way to update to latest?

### ISSUE THREAD

**Issue by r0n0c** [cdubz/babybuddy#65]
I have a running setup using the manual method. A couple users, a couple kids, but I'd like to update to the latest with the temperature tracking.

Do I just need to run a `git pull origin master` and reboot? Or is there DJANGO settings to export again?

**Comment by cdubz** [comment]
You'll need to run database migrations as well. If you followed the manual instructions exactly, just run the following from the app root after your `git pull` --

```
export DJANGO_SETTINGS_MODULE=babybuddy.settings.production
python manage.py migrate
```

I'm actually not 100% if restarting services is necessary, but you may need to restart nginx and uwsgi (or just reboot if you have trouble).

**Comment by r0n0c** [comment]
Thank you, it looks like I ran into an issue when doing the migrate. I thought it was related to the database being open and used since the site was running. I stopped and started nginx and uwsgi and although I still get the errors when trying to run the migrate, the Tempature is listed under the Children menu now.

So I am 95% sure it worked.

`ronoc@bbz:~$ cd /var/www/babybuddy/public/
ronoc@bbz:/var/www/babybuddy/public$ git pull
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 61 (delta 36), reused 60 (delta 35), pack-reused 0
Unpacking objects: 100% (61/61), done.
From https://github.com/cdubz/babybuddy
   4c1b333..c8611fa  master     -> origin/master
Updating 4c1b333..c8611fa
Fast-forward
 .travis.yml                                         |    1 +
 README.md                                           |    1 +
 api/serializers.py                                  |    6 +
 api/tests.py                                        |   35 +
 api/urls.py                                         |    1 +
 api/views.py                                        |    6 +
 babybuddy/fixtures/tests.json                       |   10 +
 babybuddy/management/commands/fake.py               |   26 +-
 babybuddy/static_src/scss/icons.scss                |    4 +
 babybuddy/templates/babybuddy/nav-dropdown.html     |   20 +
 core/admin.py                                       |    7 +
 core/forms.py                                       |   16 +
 core/migrations/0007_temperature.py                 |   29 +
 core/models.py                                      |   34 +
 core/templates/core/temperature_confirm_delete.html |   18 +
 core/templates/core/temperature_form.html           |   39 +
 core/templates/core/temperature_list.html           |   63 +
 core/tests/tests_forms.py                           |   11 +
 core/tests/tests_models.py                          |   20 +
 core/tests/tests_views.py                           |   12 +
 core/urls.py                                        |   21 +
 core/views.py                                       |   30 +
 runtime.txt                                         |    1 +
 static/admin/fonts/LICENSE.d273d63619c9.txt.gz      |  Bin 3982 -> 3968 bytes
 static/admin/fonts/LICENSE.txt.gz                   |  Bin 3982 -> 3968 bytes
 static/babybuddy/css/app.16b7aa6d5a19.css           | 9789 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 static/babybuddy/css/app.3349e431532d.css           | 9789 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 static/babybuddy/css/app.3349e431532d.css.gz        |  Bin 0 -> 34716 bytes
 static/babybuddy/css/vendor.css.gz                  |  Bin 1588 -> 1581 bytes
 static/babybuddy/js/graph.892051c17788.js.gz        |  Bin 642873 -> 642827 bytes
 static/babybuddy/js/graph.js.gz                     |  Bin 642873 -> 642827 bytes
 static/babybuddy/js/vendor.3aed05379df2.js.gz       |  Bin 179002 -> 178984 bytes
 static/babybuddy/js/vendor.js.gz                    |  Bin 179002 -> 178984 bytes
 static/staticfiles.json                             |    2 +-
 34 files changed, 19987 insertions(+), 4 deletions(-)
 create mode 100644 core/migrations/0007_temperature.py
 create mode 100644 core/templates/core/temperature_confirm_delete.html
 create mode 100644 core/templates/core/temperature_form.html
 create mode 100644 core/templates/core/temperature_list.html
 create mode 100644 runtime.txt
 create mode 100644 static/babybuddy/css/app.16b7aa6d5a19.css
 create mode 100644 static/babybuddy/css/app.3349e431532d.css
 create mode 100644 static/babybuddy/css/app.3349e431532d.css.gz
ronoc@bbz:/var/www/babybuddy/public$ pipenv shell
Launching subshell in virtual environment…
ronoc@bbz:/var/www/babybuddy/public$  . /home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/bin/activate
(public) ronoc@bbz:/var/www/babybuddy/public$ export DJANGO_SETTINGS_MODULE=babybuddy.settings.production
(public) ronoc@bbz:/var/www/babybuddy/public$ python manage.py migrate
Traceback (most recent call last):
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 194, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/www/babybuddy/public/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/ronoc/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 194, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
(public) ronoc@bbz:/var/www/babybuddy/public$ exit
exit
ronoc@bbz:/var/www/babybuddy/public$ git pull
Already up to date.
ronoc@bbz:/var/www/babybuddy/public$ export DJANGO_SETTINGS_MODULE=babybuddy.settings.production
ronoc@bbz:/var/www/babybuddy/public$ alias python=python3 
ronoc@bbz:/var/www/babybuddy/public$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from dotenv import load_dotenv, find_dotenv
ModuleNotFoundError: No module named 'dotenv'`

**Comment by fs1** [comment]
> You'll need to run database migrations as well. If you followed the manual instructions exactly, just run the following from the app root after your `git pull` --
> 
> ```
> export DJANGO_SETTINGS_MODULE=babybuddy.settings.production
> python manage.py migrate
> ```
> 
> I'm actually not 100% if restarting services is necessary, but you may need to restart nginx and uwsgi (or just reboot if you have trouble).

Was looking for exact this information, since I have babybuddy installed the manual way, too. Restarting was indeed necessary.
Maybe it's worth to write down the steps somewhere in https://docs.baby-buddy.net/?

**Comment by cdubz** [comment]
Yes this really does need to get documented... I've been hoping to find time to figure out how to make the upgrade process _simpler_ before doing that but just haven't been able to get there.

I think this is the most complete explanation to date: https://github.com/babybuddy/babybuddy/discussions/593#discussioncomment-4846498
